import { NewFieldConfig } from "@/src/lib/db/schema";

/**
 * Generate default field configurations for a new workspace
 * Based on the Task type in project.ts
 */
export function getDefaultFieldConfigs(workspaceId: string): Omit<NewFieldConfig, "id" | "createdAt" | "updatedAt">[] {
  return [
    {
      workspaceId,
      key: "title",
      name: "Title",
      type: "text",
      options: { required: true },
      order: 0,
    },
    {
      workspaceId,
      key: "owner",
      name: "Owner",
      type: "select",
      options: { choices: [], required: true },
      order: 1,
    },
    {
      workspaceId,
      key: "status",
      name: "Status",
      type: "select",
      options: {
        choices: ["todo", "in-progress", "testing", "done", "completed", "blocked"],
        defaultValue: "todo",
        required: true,
      },
      order: 2,
    },
    {
      workspaceId,
      key: "priority",
      name: "Priority",
      type: "select",
      options: {
        choices: ["low", "medium", "high", "urgent"],
        defaultValue: "medium",
        required: true,
      },
      order: 3,
    },
    {
      workspaceId,
      key: "assetClass",
      name: "Asset Class",
      type: "select",
      options: { choices: [], required: false },
      order: 4,
    },
    {
      workspaceId,
      key: "theme",
      name: "Theme",
      type: "select",
      options: { choices: [], required: false },
      order: 5,
    },
    {
      workspaceId,
      key: "teamsInvolved",
      name: "Teams Involved",
      type: "multiselect",
      options: { choices: [], required: false },
      order: 6,
    },
    {
      workspaceId,
      key: "problemStatement",
      name: "Problem Statement",
      type: "text",
      options: { required: false },
      order: 7,
    },
    {
      workspaceId,
      key: "solutionDesign",
      name: "Solution Design",
      type: "text",
      options: { required: false },
      order: 8,
    },
    {
      workspaceId,
      key: "benefits",
      name: "Benefits",
      type: "text",
      options: { required: false },
      order: 9,
    },
    {
      workspaceId,
      key: "currentHrs",
      name: "Estimated Hours",
      type: "number",
      options: { defaultValue: 0, required: false },
      order: 10,
    },
    {
      workspaceId,
      key: "workedHrs",
      name: "Worked Hours",
      type: "number",
      options: { defaultValue: 0, required: false },
      order: 11,
    },
    {
      workspaceId,
      key: "savedHrs",
      name: "Saved Hours",
      type: "number",
      options: { defaultValue: 0, required: false },
      order: 12,
    },
    {
      workspaceId,
      key: "tools",
      name: "Tools",
      type: "multiselect",
      options: { choices: [], required: false },
      order: 13,
    },
    {
      workspaceId,
      key: "tags",
      name: "Tags",
      type: "multiselect",
      options: { choices: [], required: false },
      order: 14,
    },
    {
      workspaceId,
      key: "otherUseCases",
      name: "Other Use Cases",
      type: "text",
      options: { required: false },
      order: 15,
    },
    {
      workspaceId,
      key: "completionDate",
      name: "Completion Date",
      type: "date",
      options: { required: false },
      order: 16,
    },
  ];
}
