import { NewFieldConfig } from "@/src/lib/db/schema";

/**
 * Generate default field configurations for a new workspace
 * Based on the Task type in project.ts
 */
export function getDefaultFieldConfigs(
  workspaceId: string,
): Omit<NewFieldConfig, "id" | "createdAt" | "updatedAt">[] {
  return [
    {
      workspaceId,
      key: "title",
      name: "Title",
      type: "text",
      options: { required: true },
      order: 0,
      visible: true,
      cellType: "editable-text",
    },
    {
      workspaceId,
      key: "owner",
      name: "Owner",
      type: "select",
      options: { choices: [], required: true },
      order: 1,
      visible: true,
      cellType: "editable-owner",
    },
    {
      workspaceId,
      key: "status",
      name: "Status",
      type: "select",
      options: {
        choices: [
          "todo",
          "in-progress",
          "testing",
          "done",
          "completed",
          "blocked",
        ],
        defaultValue: "todo",
        required: true,
      },
      order: 2,
      visible: true,
      cellType: "status",
    },
    {
      workspaceId,
      key: "priority",
      name: "Priority",
      type: "select",
      options: {
        choices: ["low", "medium", "high", "urgent"],
        defaultValue: "medium",
        required: true,
      },
      order: 3,
      visible: true,
      cellType: "priority",
    },
    {
      workspaceId,
      key: "assetClass",
      name: "Asset Class",
      type: "select",
      options: { choices: [], required: false },
      order: 4,
      visible: true,
      cellType: "editable-combobox",
    },
    {
      workspaceId,
      key: "theme",
      name: "Theme",
      type: "select",
      options: { choices: [], required: false },
      order: 5,
      visible: false,
      cellType: "editable-combobox",
    },
    {
      workspaceId,
      key: "teamsInvolved",
      name: "Teams Involved",
      type: "multiselect",
      options: { choices: [], required: false },
      order: 6,
      visible: true,
      cellType: "badge-list",
    },
    {
      workspaceId,
      key: "problemStatement",
      name: "Problem Statement",
      type: "text",
      options: { required: false },
      order: 7,
      visible: false,
      cellType: "editable-text",
    },
    {
      workspaceId,
      key: "solutionDesign",
      name: "Solution Design",
      type: "text",
      options: { required: false },
      order: 8,
      visible: false,
      cellType: "editable-text",
    },
    {
      workspaceId,
      key: "benefits",
      name: "Benefits",
      type: "text",
      options: { required: false },
      order: 9,
      visible: false,
      cellType: "editable-text",
    },
    {
      workspaceId,
      key: "currentHrs",
      name: "Estimated Hours",
      type: "number",
      options: { defaultValue: 0, required: false, suffix: "h" },
      order: 10,
      visible: true,
      cellType: "editable-number",
    },
    {
      workspaceId,
      key: "workedHrs",
      name: "Worked Hours",
      type: "number",
      options: { defaultValue: 0, required: false, suffix: "h" },
      order: 11,
      visible: true,
      cellType: "editable-number",
    },
    {
      workspaceId,
      key: "savedHrs",
      name: "Saved Hours",
      type: "number",
      options: { defaultValue: 0, required: false, suffix: "h" },
      order: 12,
      visible: false,
      cellType: "editable-number",
    },
    {
      workspaceId,
      key: "tools",
      name: "Tools",
      type: "multiselect",
      options: { choices: [], required: false },
      order: 13,
      visible: false,
      cellType: "editable-tags",
    },
    {
      workspaceId,
      key: "tags",
      name: "Tags",
      type: "multiselect",
      options: { choices: [], required: false },
      order: 14,
      visible: false,
      cellType: "editable-tags",
    },
    {
      workspaceId,
      key: "otherUseCases",
      name: "Other Use Cases",
      type: "text",
      options: { required: false },
      order: 15,
      visible: false,
      cellType: "editable-text",
    },
    {
      workspaceId,
      key: "completionDate",
      name: "Completion Date",
      type: "date",
      options: { required: false },
      order: 16,
      visible: true,
      cellType: "editable-date",
    },
  ];
}
