'use client';

import { Bar, BarChart, CartesianGrid, XAxis, YAxis, Legend } from 'recharts';
import { Wrench } from 'lucide-react';

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/src/components/ui/card';
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  type ChartConfig,
} from '@/src/components/ui/chart';
import { ToolsImpactData } from '@/src/lib/types/analytics';

const chartConfig = {
  savedHrs: {
    label: 'Hours Saved',
    color: 'var(--chart-1)',
  },
  processesDemised: {
    label: 'Processes Demised',
    color: 'var(--chart-2)',
  },
} satisfies ChartConfig;

interface ToolsImpactChartProps {
  data: ToolsImpactData[];
}

export function ToolsImpactChart({ data }: ToolsImpactChartProps) {
  if (!data || data.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Wrench className="h-4 w-4" />
            Tools × Impact
          </CardTitle>
          <CardDescription>Business value generated by each tool</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex h-[300px] items-center justify-center text-muted-foreground">
            No data available
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Wrench className="h-4 w-4" />
          Tools × Impact
        </CardTitle>
        <CardDescription>Business value generated by each tool</CardDescription>
      </CardHeader>
      <CardContent>
        <ChartContainer config={chartConfig} className="h-[300px] w-full">
          <BarChart
            accessibilityLayer
            data={data}
            layout="horizontal"
            margin={{
              left: 12,
              right: 12,
            }}
          >
            <CartesianGrid horizontal={false} strokeDasharray="3 3" />
            <XAxis type="number" hide />
            <YAxis
              dataKey="tool"
              type="category"
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              width={100}
              tickFormatter={(value) =>
                value.length > 12 ? `${value.slice(0, 12)}...` : value
              }
            />
            <ChartTooltip
              cursor={false}
              content={
                <ChartTooltipContent
                  formatter={(value, name, item) => {
                    const payload = item.payload as ToolsImpactData;
                    return (
                      <div className="flex flex-col gap-1">
                        <span className="font-semibold">{payload.tool}</span>
                        <span>Hours Saved: {payload.savedHrs}</span>
                        <span>Processes: {payload.processesDemised}</span>
                        <span className="text-xs text-muted-foreground">
                          {payload.taskCount} tasks
                        </span>
                      </div>
                    );
                  }}
                />
              }
            />
            <Legend />
            <Bar
              dataKey="savedHrs"
              fill={chartConfig.savedHrs.color}
              radius={4}
            />
            <Bar
              dataKey="processesDemised"
              fill={chartConfig.processesDemised.color}
              radius={4}
            />
          </BarChart>
        </ChartContainer>
      </CardContent>
    </Card>
  );
}
