import { NewFieldConfig } from '@/src/lib/db/schema';

/**
 * Generate default field configurations for a new workspace
 * Based on the Task type in project.ts
 */
export function getDefaultFieldConfigs(
  workspaceId: string,
): Omit<NewFieldConfig, 'id' | 'createdAt' | 'updatedAt'>[] {
  return [
    {
      workspaceId,
      key: 'title',
      name: 'Title',
      type: 'editable-text',
      options: { required: true },
      order: 0,
      visible: true,
    },
    {
      workspaceId,
      key: 'owner',
      name: 'Owner',
      type: 'editable-owner',
      options: { choices: [], required: true },
      order: 1,
      visible: true,
    },
    {
      workspaceId,
      key: 'assignee',
      name: 'Assignee',
      type: 'editable-owner',
      options: { choices: [], required: false },
      order: 2,
      visible: true,
    },
    {
      workspaceId,
      key: 'status',
      name: 'Status',
      type: 'status',
      options: {
        choices: [
          'todo',
          'in-progress',
          'testing',
          'done',
          'completed',
          'blocked',
        ],
        defaultValue: 'todo',
        required: true,
      },
      order: 3,
      visible: true,
    },
    {
      workspaceId,
      key: 'priority',
      name: 'Priority',
      type: 'priority',
      options: {
        choices: ['low', 'medium', 'high', 'urgent'],
        defaultValue: 'medium',
        required: true,
      },
      order: 4,
      visible: true,
    },
    {
      workspaceId,
      key: 'assetClass',
      name: 'Asset Class',
      type: 'editable-combobox',
      options: { choices: [], required: false },
      order: 5,
      visible: true,
    },
    {
      workspaceId,
      key: 'theme',
      name: 'Theme',
      type: 'editable-combobox',
      options: { choices: [], required: false },
      order: 6,
      visible: false,
    },
    {
      workspaceId,
      key: 'teamName',
      name: 'Team Name',
      type: 'editable-combobox',
      options: { choices: [], required: false },
      order: 7,
      visible: true,
    },
    {
      workspaceId,
      key: 'problemStatement',
      name: 'Problem Statement',
      type: 'editable-text',
      options: { required: false },
      order: 8,
      visible: false,
    },
    {
      workspaceId,
      key: 'solutionDesign',
      name: 'Solution Design',
      type: 'editable-text',
      options: { required: false },
      order: 9,
      visible: false,
    },
    {
      workspaceId,
      key: 'benefits',
      name: 'Benefits',
      type: 'editable-text',
      options: { required: false },
      order: 10,
      visible: false,
    },
    {
      workspaceId,
      key: 'processesDemised',
      name: 'Processes Demised',
      type: 'editable-number',
      options: { defaultValue: 0, required: false },
      order: 11,
      visible: true,
    },
    {
      workspaceId,
      key: 'savedHrs',
      name: 'Saved Hours',
      type: 'editable-number',
      options: { defaultValue: 0, required: false, suffix: 'h' },
      order: 12,
      visible: true,
    },
    {
      workspaceId,
      key: 'tools',
      name: 'Tools',
      type: 'editable-tags',
      options: { choices: [], required: false },
      order: 13,
      visible: false,
    },
    {
      workspaceId,
      key: 'tags',
      name: 'Tags',
      type: 'editable-tags',
      options: { choices: [], required: false },
      order: 14,
      visible: false,
    },
    {
      workspaceId,
      key: 'otherUseCases',
      name: 'Other Use Cases',
      type: 'editable-text',
      options: { required: false },
      order: 15,
      visible: false,
    },
    {
      workspaceId,
      key: 'completionDate',
      name: 'Completion Date',
      type: 'editable-date',
      options: { required: false },
      order: 16,
      visible: true,
    },
  ];
}
